export const Resources = {
    Loading: "Loading...",
    goToToday: "Go to today",
    invalidInputErrorMessage: "Invalid date value specified.",
    isRequiredErrorMessage: "A valid date is required",
    isOutOfBoundsErrorMessage: "Selected date is not within the valid range",
    DatePickerCalloutLabel: "Date Picker Callout",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    jun: "Jun",
    jul: "Jul",
    aug: "Aug",
    sep: "Sep",
    oct: "Oct",
    nov: "Nov",
    dec: "Dec",
    prevMonthAriaLabel: "Go to previous month",
    nextMonthAriaLabel: "Go to next month",
    prevYearAriaLabel: "Go to previous year",
    nextYearAriaLabel: "Go to next year",
};

export function datePickerStrings() {
    return {
        months: [ Resources.january, Resources.february, Resources.march, Resources.april, Resources.may, Resources.june, Resources.july, Resources.august, Resources.september, Resources.october, Resources.november, Resources.december ],
        shortMonths: [ Resources.jan, Resources.feb, Resources.mar, Resources.apr, Resources.may, Resources.jun, Resources.jul, Resources.aug, Resources.sep, Resources.oct, Resources.nov, Resources.dec ],
        days: [ Resources.sunday, Resources.monday, Resources.tuesday, Resources.wednesday, Resources.thursday, Resources.friday, Resources.saturday ],
        shortDays: [ Resources.sun, Resources.mon, Resources.tue, Resources.wed, Resources.thu, Resources.fri, Resources.sat ],
        goToToday: Resources.goToToday,
        prevMonthAriaLabel: Resources.prevMonthAriaLabel,
        nextMonthAriaLabel: Resources.nextMonthAriaLabel,
        prevYearAriaLabel: Resources.prevYearAriaLabel,
        nextYearAriaLabel: Resources.nextYearAriaLabel
    }
}
