trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

variables:
- group: azure-repos-sync

jobs:
- job: Build
  displayName: "Publish Sdk Packages"

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '-c Release -p:Version=0.0.$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)'
    displayName: 'Package for NuGet'

  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with NuGet Feed'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '5f8d36de-7004-4c36-a8b5-8a4bda9eb598/c2949ad7-bda3-4f23-a41b-3109c9419cb7'
      allowPackageConflicts: true
    displayName: 'Push to NuGet Feed'

- job: Sync
  displayName: "Sync with Azure Repos"

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        git remote add target https://tlylz:$(SYNC_PAT)@dev.azure.com/tlylz/namomo/_git/plagiarism
        git checkout $(Build.SourceBranchName)
        git pull target $(Build.SourceBranchName) --tags
        git push target --all
        git push target HEAD:$(Build.SourceBranchName) --tags
    displayName: 'Sync via Git Tools'
